[2024-11-12T04:10:18.870+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T04:10:18.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T04:10:03.168915+00:00 [queued]>
[2024-11-12T04:10:18.891+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T04:10:03.168915+00:00 [queued]>
[2024-11-12T04:10:18.891+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T04:10:18.896+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-12 04:10:03.168915+00:00
[2024-11-12T04:10:18.900+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_snapshot', 'manual__2024-11-12T04:10:03.168915+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp_tpbt3wm']
[2024-11-12T04:10:18.901+0000] {standard_task_runner.py:91} INFO - Job 237: Subtask dbt_snapshot
[2024-11-12T04:10:18.901+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=460) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T04:10:18.902+0000] {standard_task_runner.py:63} INFO - Started process 461 to run task
[2024-11-12T04:10:18.919+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T04:10:03.168915+00:00 [running]> on host c4dbd180ae41
[2024-11-12T04:10:18.948+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T04:10:03.168915+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T04:10:03.168915+00:00'
[2024-11-12T04:10:18.948+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T04:10:18.955+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T04:10:18.956+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/lab --project-dir /opt/***/lab']
[2024-11-12T04:10:18.960+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T04:10:20.017+0000] {subprocess.py:93} INFO - [0m04:10:20  Running with dbt=1.8.7
[2024-11-12T04:10:20.497+0000] {subprocess.py:93} INFO - [0m04:10:20  Registered adapter: snowflake=1.8.4
[2024-11-12T04:10:20.707+0000] {subprocess.py:93} INFO - [0m04:10:20  Found 3 models, 1 snapshot, 1 test, 2 sources, 459 macros
[2024-11-12T04:10:20.708+0000] {subprocess.py:93} INFO - [0m04:10:20
[2024-11-12T04:10:22.738+0000] {subprocess.py:93} INFO - [0m04:10:22  Concurrency: 1 threads (target='dev')
[2024-11-12T04:10:22.740+0000] {subprocess.py:93} INFO - [0m04:10:22
[2024-11-12T04:10:22.754+0000] {subprocess.py:93} INFO - [0m04:10:22  1 of 1 START snapshot snapshot.snapshot_session_summary ........................ [RUN]
[2024-11-12T04:10:23.469+0000] {subprocess.py:93} INFO - [0m04:10:23  1 of 1 ERROR snapshotting snapshot.snapshot_session_summary .................... [[31mERROR[0m in 0.71s]
[2024-11-12T04:10:23.474+0000] {subprocess.py:93} INFO - [0m04:10:23
[2024-11-12T04:10:23.475+0000] {subprocess.py:93} INFO - [0m04:10:23  Finished running 1 snapshot in 0 hours 0 minutes and 2.77 seconds (2.77s).
[2024-11-12T04:10:23.508+0000] {subprocess.py:93} INFO - [0m04:10:23
[2024-11-12T04:10:23.509+0000] {subprocess.py:93} INFO - [0m04:10:23  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-12T04:10:23.509+0000] {subprocess.py:93} INFO - [0m04:10:23
[2024-11-12T04:10:23.510+0000] {subprocess.py:93} INFO - [0m04:10:23    Database Error in snapshot snapshot_session_summary (snapshots/snapshot.macd_calculation.sql)
[2024-11-12T04:10:23.510+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 7 at position 33
[2024-11-12T04:10:23.510+0000] {subprocess.py:93} INFO -   invalid identifier 'TS'
[2024-11-12T04:10:23.510+0000] {subprocess.py:93} INFO - [0m04:10:23
[2024-11-12T04:10:23.510+0000] {subprocess.py:93} INFO - [0m04:10:23  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-11-12T04:10:24.143+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-12T04:10:24.147+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T04:10:24.156+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-12T04:10:24.159+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_snapshot, run_id=manual__2024-11-12T04:10:03.168915+00:00, execution_date=20241112T041003, start_date=20241112T041018, end_date=20241112T041024
[2024-11-12T04:10:24.167+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 237 for task dbt_snapshot (Bash command failed. The command returned a non-zero exit code 1.; 461)
[2024-11-12T04:10:24.200+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T04:10:24.216+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T04:10:24.217+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
