[2024-11-10T21:59:00.630+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T21:59:22.092+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline_STOCK_ETL.trigger_pipeline_continuation manual__2024-11-10T21:55:43.612957+00:00 [queued]>
[2024-11-10T21:59:22.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline_STOCK_ETL.trigger_pipeline_continuation manual__2024-11-10T21:55:43.612957+00:00 [queued]>
[2024-11-10T21:59:22.277+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-10T21:59:22.603+0000] {taskinstance.py:2330} INFO - Executing <Task(TriggerDagRunOperator): trigger_pipeline_continuation> on 2024-11-10 21:55:43.612957+00:00
[2024-11-10T21:59:22.721+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1437) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T21:59:22.755+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Pipeline_STOCK_ETL', 'trigger_pipeline_continuation', 'manual__2024-11-10T21:55:43.612957+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_ETL_Lab2.py', '--cfg-path', '/tmp/tmpg5slbeb4']
[2024-11-10T21:59:22.754+0000] {standard_task_runner.py:63} INFO - Started process 1453 to run task
[2024-11-10T21:59:22.764+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask trigger_pipeline_continuation
[2024-11-10T21:59:23.430+0000] {task_command.py:426} INFO - Running <TaskInstance: Pipeline_STOCK_ETL.trigger_pipeline_continuation manual__2024-11-10T21:55:43.612957+00:00 [running]> on host 64c676815d01
[2024-11-10T21:59:23.875+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline_STOCK_ETL' AIRFLOW_CTX_TASK_ID='trigger_pipeline_continuation' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T21:55:43.612957+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T21:55:43.612957+00:00'
[2024-11-10T21:59:23.886+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T21:59:24.279+0000] {trigger_dagrun.py:222} INFO - Waiting for BuildELT_dbt on 2024-11-10 21:59:23.895149+00:00 to become allowed state ['success'] ...
[2024-11-10T22:00:45.168+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T22:01:01.430+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 233, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: BuildELT_dbt failed with failed states failed
[2024-11-10T22:01:03.019+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Pipeline_STOCK_ETL, task_id=trigger_pipeline_continuation, run_id=manual__2024-11-10T21:55:43.612957+00:00, execution_date=20241110T215543, start_date=20241110T215922, end_date=20241110T220102
[2024-11-10T22:01:05.494+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 145 for task trigger_pipeline_continuation (BuildELT_dbt failed with failed states failed; 1453)
[2024-11-10T22:01:05.533+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-10T22:01:05.815+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T22:01:05.820+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
