[2024-11-06T05:41:08.350+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: YfinanceToSnowflake.load scheduled__2024-10-24T02:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
