[2024-11-12T03:43:30.406+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T03:43:30.443+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T03:43:14.039386+00:00 [queued]>
[2024-11-12T03:43:30.447+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T03:43:14.039386+00:00 [queued]>
[2024-11-12T03:43:30.447+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T03:43:30.452+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-12 03:43:14.039386+00:00
[2024-11-12T03:43:30.457+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_snapshot', 'manual__2024-11-12T03:43:14.039386+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp9hg0y5s0']
[2024-11-12T03:43:30.458+0000] {standard_task_runner.py:91} INFO - Job 219: Subtask dbt_snapshot
[2024-11-12T03:43:30.458+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1719) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T03:43:30.459+0000] {standard_task_runner.py:63} INFO - Started process 1720 to run task
[2024-11-12T03:43:30.479+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T03:43:14.039386+00:00 [running]> on host 9e7793b7ec1a
[2024-11-12T03:43:30.510+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T03:43:14.039386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T03:43:14.039386+00:00'
[2024-11-12T03:43:30.510+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T03:43:30.517+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T03:43:30.517+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/lab --project-dir /opt/***/lab']
[2024-11-12T03:43:30.521+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T03:43:31.497+0000] {subprocess.py:93} INFO - [0m03:43:31  Running with dbt=1.8.7
[2024-11-12T03:43:31.943+0000] {subprocess.py:93} INFO - [0m03:43:31  Registered adapter: snowflake=1.8.4
[2024-11-12T03:43:32.145+0000] {subprocess.py:93} INFO - [0m03:43:32  Found 3 models, 1 snapshot, 1 test, 2 sources, 459 macros
[2024-11-12T03:43:32.146+0000] {subprocess.py:93} INFO - [0m03:43:32
[2024-11-12T03:43:34.661+0000] {subprocess.py:93} INFO - [0m03:43:34  Concurrency: 1 threads (target='dev')
[2024-11-12T03:43:34.662+0000] {subprocess.py:93} INFO - [0m03:43:34
[2024-11-12T03:43:34.682+0000] {subprocess.py:93} INFO - [0m03:43:34  1 of 1 START snapshot snapshot.snapshot_session_summary ........................ [RUN]
[2024-11-12T03:43:35.263+0000] {subprocess.py:93} INFO - [0m03:43:35  1 of 1 ERROR snapshotting snapshot.snapshot_session_summary .................... [[31mERROR[0m in 0.58s]
[2024-11-12T03:43:35.267+0000] {subprocess.py:93} INFO - [0m03:43:35
[2024-11-12T03:43:35.267+0000] {subprocess.py:93} INFO - [0m03:43:35  Finished running 1 snapshot in 0 hours 0 minutes and 3.12 seconds (3.12s).
[2024-11-12T03:43:35.289+0000] {subprocess.py:93} INFO - [0m03:43:35
[2024-11-12T03:43:35.289+0000] {subprocess.py:93} INFO - [0m03:43:35  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-12T03:43:35.289+0000] {subprocess.py:93} INFO - [0m03:43:35
[2024-11-12T03:43:35.290+0000] {subprocess.py:93} INFO - [0m03:43:35    Database Error in snapshot snapshot_session_summary (snapshots/snapshot.macd_calculation.sql)
[2024-11-12T03:43:35.290+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 7 at position 33
[2024-11-12T03:43:35.290+0000] {subprocess.py:93} INFO -   invalid identifier 'TS'
[2024-11-12T03:43:35.290+0000] {subprocess.py:93} INFO - [0m03:43:35
[2024-11-12T03:43:35.290+0000] {subprocess.py:93} INFO - [0m03:43:35  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-11-12T03:43:35.920+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-12T03:43:35.921+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T03:43:35.932+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-12T03:43:35.935+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_snapshot, run_id=manual__2024-11-12T03:43:14.039386+00:00, execution_date=20241112T034314, start_date=20241112T034330, end_date=20241112T034335
[2024-11-12T03:43:35.946+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 219 for task dbt_snapshot (Bash command failed. The command returned a non-zero exit code 1.; 1720)
[2024-11-12T03:43:35.980+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T03:43:35.991+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T03:43:35.992+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
