[2024-11-10T23:06:31.856+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T23:06:31.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline_STOCK_ETL.trigger_pipeline_continuation manual__2024-11-10T23:04:46.676805+00:00 [queued]>
[2024-11-10T23:06:31.896+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline_STOCK_ETL.trigger_pipeline_continuation manual__2024-11-10T23:04:46.676805+00:00 [queued]>
[2024-11-10T23:06:31.897+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-10T23:06:31.905+0000] {taskinstance.py:2330} INFO - Executing <Task(TriggerDagRunOperator): trigger_pipeline_continuation> on 2024-11-10 23:04:46.676805+00:00
[2024-11-10T23:06:31.918+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Pipeline_STOCK_ETL', 'trigger_pipeline_continuation', 'manual__2024-11-10T23:04:46.676805+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_ETL_Lab2.py', '--cfg-path', '/tmp/tmp7mzf9uv1']
[2024-11-10T23:06:31.924+0000] {standard_task_runner.py:91} INFO - Job 158: Subtask trigger_pipeline_continuation
[2024-11-10T23:06:31.920+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2104) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-10T23:06:31.924+0000] {standard_task_runner.py:63} INFO - Started process 2107 to run task
[2024-11-10T23:06:31.972+0000] {task_command.py:426} INFO - Running <TaskInstance: Pipeline_STOCK_ETL.trigger_pipeline_continuation manual__2024-11-10T23:04:46.676805+00:00 [running]> on host 599a8e9540bd
[2024-11-10T23:06:32.078+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline_STOCK_ETL' AIRFLOW_CTX_TASK_ID='trigger_pipeline_continuation' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T23:04:46.676805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T23:04:46.676805+00:00'
[2024-11-10T23:06:32.080+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T23:06:32.134+0000] {trigger_dagrun.py:222} INFO - Waiting for BuildELT_dbt on 2024-11-10 23:06:32.080549+00:00 to become allowed state ['success'] ...
[2024-11-10T23:07:32.187+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T23:07:32.208+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 233, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: BuildELT_dbt failed with failed states failed
[2024-11-10T23:07:32.220+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Pipeline_STOCK_ETL, task_id=trigger_pipeline_continuation, run_id=manual__2024-11-10T23:04:46.676805+00:00, execution_date=20241110T230446, start_date=20241110T230631, end_date=20241110T230732
[2024-11-10T23:07:32.237+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 158 for task trigger_pipeline_continuation (BuildELT_dbt failed with failed states failed; 2107)
[2024-11-10T23:07:32.268+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-10T23:07:32.291+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T23:07:32.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
