[2024-11-12T04:07:41.388+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T04:07:41.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T04:07:40.429525+00:00 [queued]>
[2024-11-12T04:07:41.406+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T04:07:40.429525+00:00 [queued]>
[2024-11-12T04:07:41.407+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T04:07:41.412+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 04:07:40.429525+00:00
[2024-11-12T04:07:41.420+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-12T04:07:40.429525+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp3x1_2z76']
[2024-11-12T04:07:41.424+0000] {standard_task_runner.py:91} INFO - Job 231: Subtask dbt_run
[2024-11-12T04:07:41.423+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=382) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T04:07:41.425+0000] {standard_task_runner.py:63} INFO - Started process 383 to run task
[2024-11-12T04:07:41.458+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T04:07:40.429525+00:00 [running]> on host a8380877cd37
[2024-11-12T04:07:41.505+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T04:07:40.429525+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T04:07:40.429525+00:00'
[2024-11-12T04:07:41.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T04:07:41.514+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T04:07:41.514+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/lab --project-dir /opt/***/lab']
[2024-11-12T04:07:41.519+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T04:07:42.565+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-11-12T04:07:42.565+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-11-12T04:07:42.566+0000] {subprocess.py:93} INFO - 
[2024-11-12T04:07:42.566+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/***/lab' does not exist.
[2024-11-12T04:07:42.654+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T04:07:42.655+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T04:07:42.661+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T04:07:42.663+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-12T04:07:40.429525+00:00, execution_date=20241112T040740, start_date=20241112T040741, end_date=20241112T040742
[2024-11-12T04:07:42.669+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 231 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 383)
[2024-11-12T04:07:42.688+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T04:07:42.698+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T04:07:42.699+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
