[2024-11-12T04:13:10.512+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T04:13:10.526+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T04:12:56.943103+00:00 [queued]>
[2024-11-12T04:13:10.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T04:12:56.943103+00:00 [queued]>
[2024-11-12T04:13:10.529+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T04:13:10.533+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-12 04:12:56.943103+00:00
[2024-11-12T04:13:10.537+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_snapshot', 'manual__2024-11-12T04:12:56.943103+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpev9ckkm7']
[2024-11-12T04:13:10.538+0000] {standard_task_runner.py:91} INFO - Job 243: Subtask dbt_snapshot
[2024-11-12T04:13:10.538+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=777) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T04:13:10.539+0000] {standard_task_runner.py:63} INFO - Started process 778 to run task
[2024-11-12T04:13:10.556+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T04:12:56.943103+00:00 [running]> on host c4dbd180ae41
[2024-11-12T04:13:10.585+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T04:12:56.943103+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T04:12:56.943103+00:00'
[2024-11-12T04:13:10.586+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T04:13:10.592+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T04:13:10.592+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/lab --project-dir /opt/***/lab']
[2024-11-12T04:13:10.595+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T04:13:11.512+0000] {subprocess.py:93} INFO - [0m04:13:11  Running with dbt=1.8.7
[2024-11-12T04:13:11.914+0000] {subprocess.py:93} INFO - [0m04:13:11  Registered adapter: snowflake=1.8.4
[2024-11-12T04:13:12.096+0000] {subprocess.py:93} INFO - [0m04:13:12  Found 3 models, 1 test, 1 snapshot, 2 sources, 459 macros
[2024-11-12T04:13:12.097+0000] {subprocess.py:93} INFO - [0m04:13:12
[2024-11-12T04:13:14.016+0000] {subprocess.py:93} INFO - [0m04:13:14  Concurrency: 1 threads (target='dev')
[2024-11-12T04:13:14.019+0000] {subprocess.py:93} INFO - [0m04:13:14
[2024-11-12T04:13:14.037+0000] {subprocess.py:93} INFO - [0m04:13:14  1 of 1 START snapshot snapshot.snapshot_macd_calculation ....................... [RUN]
[2024-11-12T04:13:14.659+0000] {subprocess.py:93} INFO - [0m04:13:14  1 of 1 ERROR snapshotting snapshot.snapshot_macd_calculation ................... [[31mERROR[0m in 0.62s]
[2024-11-12T04:13:14.666+0000] {subprocess.py:93} INFO - [0m04:13:14
[2024-11-12T04:13:14.667+0000] {subprocess.py:93} INFO - [0m04:13:14  Finished running 1 snapshot in 0 hours 0 minutes and 2.57 seconds (2.57s).
[2024-11-12T04:13:14.701+0000] {subprocess.py:93} INFO - [0m04:13:14
[2024-11-12T04:13:14.702+0000] {subprocess.py:93} INFO - [0m04:13:14  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-12T04:13:14.702+0000] {subprocess.py:93} INFO - [0m04:13:14
[2024-11-12T04:13:14.703+0000] {subprocess.py:93} INFO - [0m04:13:14    Database Error in snapshot snapshot_macd_calculation (snapshots/snapshot.macd_calculation.sql)
[2024-11-12T04:13:14.703+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 7 at position 33
[2024-11-12T04:13:14.703+0000] {subprocess.py:93} INFO -   invalid identifier 'TS'
[2024-11-12T04:13:14.703+0000] {subprocess.py:93} INFO - [0m04:13:14
[2024-11-12T04:13:14.703+0000] {subprocess.py:93} INFO - [0m04:13:14  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-11-12T04:13:15.370+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-12T04:13:15.371+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T04:13:15.386+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-12T04:13:15.392+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_snapshot, run_id=manual__2024-11-12T04:12:56.943103+00:00, execution_date=20241112T041256, start_date=20241112T041310, end_date=20241112T041315
[2024-11-12T04:13:15.403+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 243 for task dbt_snapshot (Bash command failed. The command returned a non-zero exit code 1.; 778)
[2024-11-12T04:13:15.441+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T04:13:15.462+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T04:13:15.463+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
