[2024-11-12T20:04:37.328+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T20:04:37.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T20:04:36.214402+00:00 [queued]>
[2024-11-12T20:04:37.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T20:04:36.214402+00:00 [queued]>
[2024-11-12T20:04:37.352+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T20:04:37.358+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 20:04:36.214402+00:00
[2024-11-12T20:04:37.361+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-12T20:04:36.214402+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpv7ugvach']
[2024-11-12T20:04:37.364+0000] {standard_task_runner.py:91} INFO - Job 291: Subtask dbt_run
[2024-11-12T20:04:37.363+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1490) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T20:04:37.365+0000] {standard_task_runner.py:63} INFO - Started process 1491 to run task
[2024-11-12T20:04:37.386+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T20:04:36.214402+00:00 [running]> on host ff1b9c31ae4f
[2024-11-12T20:04:37.433+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T20:04:36.214402+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T20:04:36.214402+00:00'
[2024-11-12T20:04:37.433+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T20:04:37.443+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T20:04:37.443+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/lab --project-dir /opt/***/lab']
[2024-11-12T20:04:37.448+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T20:04:38.428+0000] {subprocess.py:93} INFO - [0m20:04:38  Running with dbt=1.8.7
[2024-11-12T20:04:38.892+0000] {subprocess.py:93} INFO - [0m20:04:38  Registered adapter: snowflake=1.8.4
[2024-11-12T20:04:39.076+0000] {subprocess.py:93} INFO - [0m20:04:39  Encountered an error:
[2024-11-12T20:04:39.077+0000] {subprocess.py:93} INFO - Compilation Error
[2024-11-12T20:04:39.077+0000] {subprocess.py:93} INFO -   Snapshot 'snapshot.lab.snapshot_RSI_calculation' (snapshots/snapshot.RSI_calculation.sql) depends on a node named 'RSI_calculation' which was not found
[2024-11-12T20:04:39.704+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T20:04:39.705+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T20:04:39.713+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T20:04:39.717+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-12T20:04:36.214402+00:00, execution_date=20241112T200436, start_date=20241112T200437, end_date=20241112T200439
[2024-11-12T20:04:39.724+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 291 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 1491)
[2024-11-12T20:04:39.738+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T20:04:39.748+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T20:04:39.750+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
