[2024-10-24T21:05:56.214+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: SetupETLtables.createTable__1 manual__2024-10-24T21:05:19.228634+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
