[2024-10-24T22:57:22.787+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-24T22:57:22.797+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_CTAS.run_ctas manual__2024-10-24T22:57:21.567194+00:00 [queued]>
[2024-10-24T22:57:22.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_CTAS.run_ctas manual__2024-10-24T22:57:21.567194+00:00 [queued]>
[2024-10-24T22:57:22.800+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-24T22:57:22.804+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): run_ctas> on 2024-10-24 22:57:21.567194+00:00
[2024-10-24T22:57:22.809+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=483) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-24T22:57:22.810+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_CTAS', 'run_ctas', 'manual__2024-10-24T22:57:21.567194+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_ctas.py', '--cfg-path', '/tmp/tmpnd4lbcvn']
[2024-10-24T22:57:22.812+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask run_ctas
[2024-10-24T22:57:22.812+0000] {standard_task_runner.py:63} INFO - Started process 485 to run task
[2024-10-24T22:57:22.843+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_CTAS.run_ctas manual__2024-10-24T22:57:21.567194+00:00 [running]> on host 64c676815d01
[2024-10-24T22:57:22.879+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_CTAS' AIRFLOW_CTX_TASK_ID='run_ctas' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T22:57:21.567194+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-24T22:57:21.567194+00:00'
[2024-10-24T22:57:22.880+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-24T22:57:22.880+0000] {build_elt_with_ctas.py:34} INFO - dev.analytics.session_summary
[2024-10-24T22:57:22.880+0000] {build_elt_with_ctas.py:35} INFO - SELECT u.*, s.ts
    FROM dev.raw_data.user_session_channel u
    JOIN dev.raw_data.session_timestamp s ON u.sessionId=s.sessionId
    
[2024-10-24T22:57:22.886+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-10-24T22:57:22.887+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.4-linuxkit-aarch64-with-glibc2.36
[2024-10-24T22:57:22.887+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-10-24T22:57:23.746+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-10-24T22:57:23.747+0000] {build_elt_with_ctas.py:42} INFO - CREATE OR REPLACE TABLE dev.analytics.session_summary AS SELECT u.*, s.ts
    FROM dev.raw_data.user_session_channel u
    JOIN dev.raw_data.session_timestamp s ON u.sessionId=s.sessionId
    
[2024-10-24T22:57:24.277+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-10-24T22:57:24.279+0000] {build_elt_with_ctas.py:59} ERROR - Failed to sql. Completed ROLLBACK!
[2024-10-24T22:57:24.279+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-24T22:57:24.280+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/build_elt_with_ctas.py", line 43, in run_ctas
    cur.execute(sql)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b7e9e1-0004-0d75-0001-8e6b000372d6: SQL compilation error:
Schema 'DEV.ANALYTICS' does not exist or not authorized.
[2024-10-24T22:57:24.292+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_CTAS, task_id=run_ctas, run_id=manual__2024-10-24T22:57:21.567194+00:00, execution_date=20241024T225721, start_date=20241024T225722, end_date=20241024T225724
[2024-10-24T22:57:24.306+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 76 for task run_ctas (002003 (02000): 01b7e9e1-0004-0d75-0001-8e6b000372d6: SQL compilation error:
Schema 'DEV.ANALYTICS' does not exist or not authorized.; 485)
[2024-10-24T22:57:24.333+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-24T22:57:24.345+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-24T22:57:24.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
